# ref: https://eksctl.io/usage/schema/#metadata-version
# An example of ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample
  region: ap-northeast-1
  version: "1.30"

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 3
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 3

fargateProfiles:
  - name: fp-fargate
    selectors:
      # All workloads in the "fargate" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: fargate
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels:
          env: dev
          checks: passed
